//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTec.Infrastructure.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AgendaTecEntities : DbContext
    {
        public AgendaTecEntities()
            : base("name=AgendaTecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TCGCustomers> TCGCustomers { get; set; }
        public virtual DbSet<TCGCustomersAspNetUsers> TCGCustomersAspNetUsers { get; set; }
        public virtual DbSet<TCGCustomerTimeRanges> TCGCustomerTimeRanges { get; set; }
        public virtual DbSet<TCGProfessionals> TCGProfessionals { get; set; }
        public virtual DbSet<TCGServices> TCGServices { get; set; }
        public virtual DbSet<TDirectMail> TDirectMail { get; set; }
        public virtual DbSet<TProfessionalService> TProfessionalService { get; set; }
        public virtual DbSet<TSchedules> TSchedules { get; set; }
    
        public virtual ObjectResult<SP_ScheduleReport_Result> SP_ScheduleReport(Nullable<int> iDCustomer, Nullable<System.DateTime> initialDate, Nullable<System.DateTime> finalDate)
        {
            var iDCustomerParameter = iDCustomer.HasValue ?
                new ObjectParameter("IDCustomer", iDCustomer) :
                new ObjectParameter("IDCustomer", typeof(int));
    
            var initialDateParameter = initialDate.HasValue ?
                new ObjectParameter("InitialDate", initialDate) :
                new ObjectParameter("InitialDate", typeof(System.DateTime));
    
            var finalDateParameter = finalDate.HasValue ?
                new ObjectParameter("FinalDate", finalDate) :
                new ObjectParameter("FinalDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ScheduleReport_Result>("SP_ScheduleReport", iDCustomerParameter, initialDateParameter, finalDateParameter);
        }
    }
}
