//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTec.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCGJobs
    {
        public int IDJob { get; set; }
        public int IDCustomer { get; set; }
        public int IDJobType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public string JobStatus { get; set; }
        public string FileName { get; set; }
    
        public virtual TCGCustomers TCGCustomers { get; set; }
        public virtual TCGJobTypes TCGJobTypes { get; set; }
    }
}
