//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTec.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDirectMail
    {
        public int IDMail { get; set; }
        public int IDCustomer { get; set; }
        public string Description { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.DateTime> LastProcessed { get; set; }
        public int IntervalType { get; set; }
        public bool Resend { get; set; }
    
        public virtual TCGCustomers TCGCustomers { get; set; }
    }
}
