//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTec.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProfessionalService
    {
        public System.Guid IDProfesisonalService { get; set; }
        public int IDProfessional { get; set; }
        public int IDService { get; set; }
    
        public virtual TCGProfessionals TCGProfessionals { get; set; }
        public virtual TCGServices TCGServices { get; set; }
    }
}
