//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTech.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordHistories
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime DateChanged { get; set; }
        public string PasswordHash { get; set; }
    }
}
