//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTech.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCGCustomers
    {
        public int IDCustomer { get; set; }
        public string RazaoSocial { get; set; }
        public string CNPJ_CPF { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }
        public System.DateTime DataContratacao { get; set; }
        public bool Ativo { get; set; }
        public string Observacao { get; set; }
    }
}
