//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTech.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSchedules
    {
        public int IDSchedule { get; set; }
        public int IDCustomer { get; set; }
        public int IDProfessional { get; set; }
        public int IDService { get; set; }
        public System.Guid IDConsumer { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public int Time { get; set; }
        public bool Bonus { get; set; }
    
        public virtual TCGCustomers TCGCustomers { get; set; }
        public virtual TCGServices TCGServices { get; set; }
        public virtual TCGProfessionals TCGProfessionals { get; set; }
    }
}
