//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTech.Infrastructure.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccounts()
        {
            this.LinkedAccountClaims = new HashSet<LinkedAccountClaims>();
            this.LinkedAccounts = new HashSet<LinkedAccounts>();
            this.PasswordResetSecrets = new HashSet<PasswordResetSecrets>();
            this.TwoFactorAuthTokens = new HashSet<TwoFactorAuthTokens>();
            this.UserCertificates = new HashSet<UserCertificates>();
            this.UserClaims = new HashSet<UserClaims>();
        }
    
        public int Key { get; set; }
        public int Source { get; set; }
        public int Inscription { get; set; }
        public string StartingPass { get; set; }
        public System.Guid ID { get; set; }
        public string Tenant { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsAccountClosed { get; set; }
        public Nullable<System.DateTime> AccountClosed { get; set; }
        public bool IsLoginAllowed { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastFailedLogin { get; set; }
        public int FailedLoginCount { get; set; }
        public Nullable<System.DateTime> PasswordChanged { get; set; }
        public bool RequiresPasswordReset { get; set; }
        public string Email { get; set; }
        public bool IsAccountVerified { get; set; }
        public Nullable<System.DateTime> LastFailedPasswordReset { get; set; }
        public int FailedPasswordResetCount { get; set; }
        public string MobileCode { get; set; }
        public Nullable<System.DateTime> MobileCodeSent { get; set; }
        public string MobilePhoneNumber { get; set; }
        public Nullable<System.DateTime> MobilePhoneNumberChanged { get; set; }
        public int AccountTwoFactorAuthMode { get; set; }
        public int CurrentTwoFactorAuthStatus { get; set; }
        public string VerificationKey { get; set; }
        public Nullable<int> VerificationPurpose { get; set; }
        public Nullable<System.DateTime> VerificationKeySent { get; set; }
        public string VerificationStorage { get; set; }
        public string HashedPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedAccountClaims> LinkedAccountClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedAccounts> LinkedAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordResetSecrets> PasswordResetSecrets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TwoFactorAuthTokens> TwoFactorAuthTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCertificates> UserCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserClaims> UserClaims { get; set; }
    }
}
